#!/usr/bin/env bash
# kb.sh — read the records back. The loop WRITES knowledge (intent, spec, plan,
# evidence, delivery, CLOSED, lessons, harvest); this is how a later feature —
# or a human — FINDS it and reads it without opening six files.
#
#   kb.sh index   [--store <dir>] [--obsidian]       regenerate the contents page
#   kb.sh list    [--store <dir> | --area <folder>]
#   kb.sh show    <slug> [--store <dir> | --area <folder>]   one feature as a digest
#   kb.sh search  [--store <dir> | --area <folder>] [--limit N] <literal text>
#   kb.sh harvest [--store <dir> | --area <folder>] [--stale <days>]
#                                                   open features whose harvest.md is not in memory/ yet
#
# Store resolution: --store <dir> is a store (or a project's .sdlc); with
# neither flag the store is ./.sdlc. --area <folder> reads EVERY recognized
# store in that folder — a directory holding a PROJECT record written by
# init.sh --area — and nothing else: no arbitrary filesystem content, no
# symlinks followed, one level deep. The original checkout need not exist, so
# knowledge survives a deleted worktree.
#
# What is read: *.md and CLOSED under work/, archive/ and memory/.
# Never read: scratch/ (bulk evidence), approvals/ (machine records),
# progress.md (heartbeat), baseline.txt, checkpoint.md, verify-receipt.md.
#
# What a reader gets (v0.13): `show` is a digest — the goal, the feature's
# summary.md (templates/summary.md: Problem/Cause/Change/Result/Lesson, bound
# by no approval so it can stay current), delivery state, the unmerged
# harvest.md candidates, lesson titles — with the document paths last. `index` opens with
# an overview table (state, date, tags), newest first, and lists the harvests
# that no close has merged yet, so in-flight knowledge is visible from the
# entry page instead of only after `close.sh`. `--obsidian` (or
# `index_style: obsidian` in the store's config.md) adds YAML frontmatter and
# inline #tags to the generated page; links stay standard relative markdown,
# which Obsidian resolves and graphs. No timestamp is written into the page:
# a regenerated page that did not change must not produce a diff.
#
# Nothing under work/ or archive/ is ever written — an approval-bound artifact
# cannot change because the page was regenerated. `index` writes exactly one
# file, <store>/README.md, and refuses to overwrite one it did not generate.
#
# Exit codes: 0 done / matches found, 1 nothing found (no match, unknown slug,
# no unmerged harvest), 2 usage error or refusal (missing store, unowned path,
# unwritable page).
set -u

MARKER='<!-- generated by sdlc-kit tools/kb.sh — regenerated by init.sh and close.sh; edits are overwritten -->'
LINE_MAX=200
SUMMARY_MAX=12     # lines of summary.md shown by `show` / `index`
HARVEST_MAX=10     # harvest.md lines shown by `show`
HARVEST_INDEX_MAX=6 # harvest.md lines shown per feature on the contents page
TABLE_GOAL_MAX=120 # bytes of the goal kept in the overview table (≈40 CJK / 120 ASCII characters)

usage() {
  sed -n '3,11p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 2
}

# --- store resolution --------------------------------------------------------
kb_is_store() { # <dir> — a directory that holds records
  [ -d "$1/work" ] || [ -d "$1/archive" ] || [ -d "$1/memory" ]
}
kb_label() { # <store dir> → the name results are reported under
  local s="$1" p
  p=$(cd "$s" 2>/dev/null && pwd -P) || { basename "$s"; return; }
  basename "$p"
}
# Prints one store path per line, or fails with a reason on stderr.
kb_stores() { # <store-or-empty> <area-or-empty>
  local store="$1" area="$2" d n=0
  if [ -n "$area" ]; then
    [ -d "$area" ] || { echo "FAIL: no such area: $area" >&2; return 2; }
    for d in "$area"/*; do
      [ -d "$d" ] || continue
      [ -L "$d" ] && continue          # never follow a link out of the area
      [ -f "$d/PROJECT" ] || continue  # only stores this kit owns
      printf '%s\n' "$d"; n=$((n + 1))
    done
    [ "$n" -gt 0 ] || { echo "FAIL: no sdlc-kit stores in $area (a store holds a PROJECT record)" >&2; return 2; }
    return 0
  fi
  [ -n "$store" ] || store=".sdlc"
  [ -d "$store" ] || { echo "FAIL: no store at $store — run init.sh first, or pass --store/--area" >&2; return 2; }
  kb_is_store "$store" || { echo "FAIL: $store holds no work/, archive/ or memory/ — not a store" >&2; return 2; }
  printf '%s\n' "$store"
}

# --- feature reading ---------------------------------------------------------
KB_DOCS="summary.md origin.md intent.md spec.md plan.md map.md evidence.md delivery.md CLOSED"

kb_field() { # <file> <label> → the first "- <label>: value" line's value
  [ -f "$1" ] || return 1
  awk -v k="- $2:" 'index($0, k) == 1 { sub(/^[^:]*: */, ""); sub(/[ \t\r]*$/, ""); print; exit }' "$1"
}
kb_real() { # <value> → the value unless it is still a template placeholder (<…>, YYYY-…)
  case "$1" in ''|'<'*|YYYY*) printf '';; *) printf '%s' "$1";; esac
}
# Feature directories of one store: "<work|archive> <slug> <dir>" lines.
kb_features() { # <store>
  local store="$1" kind d slug
  for kind in work archive; do
    [ -d "$store/$kind" ] || continue
    for d in "$store/$kind"/*; do
      [ -d "$d" ] || continue
      if [ -L "$d" ]; then
        echo "note: skipped $d — a feature directory that is a symlink is not read" >&2
        continue
      fi
      slug=$(basename "$d")
      printf '%s %s %s\n' "$kind" "$slug" "$d"
    done
  done
}
kb_lessons() { # <store> <slug> → lesson paths naming the slug
  local d="$1/memory/lessons" f
  [ -d "$d" ] || return 0
  for f in "$d"/*"$2"*; do [ -f "$f" ] && printf '%s\n' "$f"; done
}
kb_state() { # <dir> → open | the CLOSED state
  local c="$1/CLOSED"
  if [ -f "$c" ]; then awk '/^state: /{print $2; exit}' "$c"; else echo open; fi
}
kb_h1() { # <file> [prefix to drop, e.g. "Intent: "] → the first H1, cleaned
  [ -f "$1" ] || return 0
  awk -v p="${2:-}" '/^# /{ sub(/^# */, ""); if (p != "" && index($0, p) == 1) $0 = substr($0, length(p) + 1); sub(/[ \t\r]*$/, ""); print; exit }' "$1"
}
kb_title() { # <dir> → the Goal line, else the intent's H1 (older intents have no Goal field)
  local g; g=$(kb_real "$(kb_field "$1/intent.md" Goal 2>/dev/null || true)")
  [ -n "$g" ] || g=$(kb_h1 "$1/intent.md" "Intent: ")
  printf '%s' "$g"
}
kb_date() { # <dir> <slug> → YYYY-MM-DD, from the intent's Date, else a YYMMDD- slug prefix, else empty
  local d; d=$(kb_real "$(kb_field "$1/intent.md" Date 2>/dev/null || true)")
  case "$d" in
    [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]*) printf '%s' "$(printf '%s' "$d" | cut -c1-10)"; return;;
  esac
  case "$2" in
    [0-9][0-9][0-9][0-9][0-9][0-9]-*) printf '20%s-%s-%s' "$(printf '%s' "$2" | cut -c1-2)" "$(printf '%s' "$2" | cut -c3-4)" "$(printf '%s' "$2" | cut -c5-6)"; return;;
  esac
  printf ''
}
kb_closed_at() { # <dir> → YYYY-MM-DD of the CLOSED record, or empty
  [ -f "$1/CLOSED" ] || return 0
  awk '/^closed_at: /{print substr($2, 1, 10); exit}' "$1/CLOSED"
}
kb_tags() { # <dir> → "tag, tag" — summary.md's Tags line (else the intent's), normalized
  local t; t=$(kb_real "$(kb_field "$1/summary.md" Tags 2>/dev/null || true)")
  [ -n "$t" ] || t=$(kb_real "$(kb_field "$1/intent.md" Tags 2>/dev/null || true)")
  [ -n "$t" ] || return 0
  printf '%s' "$t" | tr -d '[]' | tr ',' '\n' | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); if ($0 != "") { if (n++) printf ", "; printf "%s", $0 } }'
}
kb_hashtags() { # "tag, tag" → "#tag #tag" for Obsidian's tag pane (spaces inside a tag become -)
  printf '%s' "$1" | tr ',' '\n' | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); gsub(/[ \t]+/, "-"); if ($0 != "") { if (n++) printf " "; printf "#%s", $0 } }'
}
# The readable body of a record: template comments (single- and multi-line),
# blank lines and unfilled `<placeholder>` lines are dropped; the H1 is dropped;
# `## X` becomes `X:`. With <heading>, only that section is returned.
kb_body() { # <file> [heading]
  [ -f "$1" ] || return 0
  awk -v H="${2:-}" '
    BEGIN { c = 0; f = (H == "") ? 1 : 0 }
    {
      line = $0
      if (c) { i = index(line, "-->"); if (i) { c = 0; line = substr(line, i + 3) } else next }
      while ((s = index(line, "<!--")) > 0) {
        rest = substr(line, s); e = index(rest, "-->")
        if (e) line = substr(line, 1, s - 1) substr(rest, e + 3)
        else { line = substr(line, 1, s - 1); c = 1; break }
      }
      sub(/[ \t\r]+$/, "", line)
      if (line ~ /^## /) {
        if (H != "") { if (f) exit; if (index(line, "## " H) == 1) { f = 1 }; next }
        sub(/^## +/, "", line); print line ":"; next
      }
      if (!f) next
      if (line ~ /^# /) next
      # deeper headings (some harvests use ### per candidate) become labels too,
      # so a record embedded in the contents page cannot hijack its outline
      if (line ~ /^###+ /) { sub(/^#+ +/, "", line); print line ":"; next }
      if (line ~ /^[ \t]*$/) next
      if (line ~ /^[ \t]*[-*] *<[^>]*>[ \t]*$/) next
      if (line ~ /^[ \t]*<[^>]*>[ \t]*$/) next
      if (line ~ /^[ \t]*[-*] *[A-Za-z-]+: *<[^>]*>[ \t]*$/) next
      print line
    }' "$1"
}
kb_summary() { # <dir> → the reader's digest: summary.md, else an intent's ## Summary section (older records)
  if [ -f "$1/summary.md" ]; then kb_body "$1/summary.md" | awk '!/^[ \t]*[-*] *Tags:/'
  else kb_body "$1/intent.md" Summary; fi
}
kb_summary_where() { [ -f "$1/summary.md" ] && echo summary.md || echo intent.md; }
kb_print_bounded() { # <max> <indent> <"more" location>; text on stdin
  awk -v m="$1" -v ind="$2" -v where="$3" '
    { n++; if (n <= m) print ind $0 }
    END { if (n > m) printf "%s… %d more line(s): %s\n", ind, n - m, where }'
}
kb_count_lines() { # kb_body text on stdin → content lines (labels ending in ":" excluded)
  awk '!/:$/ { n++ } END { print n + 0 }'
}
# Idle test for the harvest report: a feature is active when any of its own
# records (not scratch/) was modified inside the window. BSD stat first (macOS),
# then GNU — the same fallback status.sh uses for the heartbeat age.
kb_mtime() { stat -f %m "$1" 2>/dev/null || stat -c %Y "$1" 2>/dev/null || true; }
kb_idle_days() { # <feature dir> → whole days since the newest record, or empty when unknown
  local f m newest=""
  for f in "$1"/*.md "$1"/CLOSED; do
    [ -f "$f" ] || continue
    m=$(kb_mtime "$f"); case "$m" in ''|*[!0-9]*) continue;; esac
    if [ -z "$newest" ] || [ "$m" -gt "$newest" ]; then newest="$m"; fi
  done
  [ -n "$newest" ] || return 0
  echo $(( ( $(date +%s) - newest ) / 86400 ))
}

# --- index -------------------------------------------------------------------
kb_index_style() { # <store> <flag> → obsidian | plain
  if [ "$2" = obsidian ]; then echo obsidian; return; fi
  if [ -f "$1/config.md" ] && awk '/^index_style:[ \t]*obsidian/{ f = 1 } END { exit !f }' "$1/config.md"; then
    echo obsidian; return
  fi
  echo plain
}
kb_table_cell() { # text → one table cell: pipes escaped, newlines gone, bounded
  # Bounded in BYTES under LC_ALL=C (awk's length/substr are not UTF-8 aware
  # everywhere); the cut backs off to a character boundary so a multibyte
  # character is never split into a broken glyph.
  printf '%s' "$1" | tr '\n\r' '  ' | sed 's/|/\\|/g' | LC_ALL=C awk -v m="$TABLE_GOAL_MAX" '{
    if (length($0) <= m) { print; next }
    i = m + 1
    while (i > 1 && substr($0, i, 1) >= "\200" && substr($0, i, 1) < "\300") i--
    print substr($0, 1, i - 1) "…" }'
}
# "<sortkey>\t<kind>\t<slug>\t<dir>" lines, newest first within each kind.
kb_features_sorted() { # <store> <kind>
  local store="$1" want="$2" kind slug dir key
  kb_features "$store" 2>/dev/null | while read -r kind slug dir; do
    [ "$kind" = "$want" ] || continue
    if [ "$kind" = archive ]; then key=$(kb_closed_at "$dir"); else key=""; fi
    [ -n "$key" ] || key=$(kb_date "$dir" "$slug")
    [ -n "$key" ] || key="0000-00-00"
    printf '%s\t%s\t%s\t%s\n' "$key" "$kind" "$slug" "$dir"
  done | LC_ALL=C sort -t "$(printf '\t')" -k1,1r -k3,3
}
kb_index() { # <store> <style>
  local store="$1" style="$2" page kind slug dir doc goal track state f date tags key when label body n_h n_stale
  page="$store/README.md"
  label=$(kb_label "$store")
  if [ -e "$page" ]; then
    if [ -L "$page" ]; then echo "FAIL: $page is a symlink — refusing to write through it" >&2; return 2; fi
    if ! head -n 12 "$page" 2>/dev/null | grep -qF "$MARKER"; then
      echo "FAIL: $page was not generated by kb.sh — refusing to overwrite a page you wrote." >&2
      echo "  Rename it (or delete it) if you want the generated contents page here." >&2
      return 2
    fi
  fi
  {
    if [ "$style" = obsidian ]; then
      # frontmatter first (Obsidian reads it only at line 1); no generated-at
      # stamp — a page whose content did not change must not produce a diff
      printf -- '---\ntitle: "Knowledge: %s"\nsdlc_store: "%s"\ntags: [sdlc-kit, knowledge]\n---\n' "$label" "$label"
    fi
    printf '%s\n' "$MARKER"
    printf '\n# Knowledge: %s\n\n' "$label"
    if [ -f "$store/PROJECT" ]; then
      printf 'Records of `%s` (checkout `%s`).\n\n' \
        "$(awk '/^project: /{sub(/^project: /,""); sub(/[ \t\r]*$/,""); print; exit}' "$store/PROJECT")" \
        "$(awk '/^checkout_id: /{print $2; exit}' "$store/PROJECT")"
    fi
    printf 'Search: `tools/kb.sh search "<text>"` · one feature: `tools/kb.sh show <slug>` · knowledge not merged yet: `tools/kb.sh harvest`\n'

    # --- overview: one row per feature, open first, newest first --------------
    printf '\n## Overview\n\n'
    printf '| Feature | State | Date | Tags | Goal |\n|---|---|---|---|---|\n'
    n_h=0
    for kind in work archive; do
      kb_features_sorted "$store" "$kind" | while IFS="$(printf '\t')" read -r key kind slug dir; do
        [ -n "${slug:-}" ] || continue
        state=$(kb_state "$dir")
        [ "$key" = "0000-00-00" ] && key="—"
        tags=$(kb_tags "$dir")
        [ "$style" = obsidian ] && [ -n "$tags" ] && tags=$(kb_hashtags "$tags")
        doc=intent.md; [ -f "$dir/intent.md" ] || doc=""
        if [ -n "$doc" ]; then printf '| [%s](%s/%s/%s) ' "$slug" "$kind" "$slug" "$doc"; else printf '| %s ' "$slug"; fi
        printf '| %s | %s | %s | %s |\n' "$state" "$key" "${tags:-—}" "$(kb_table_cell "$(kb_title "$dir")")"
      done
    done
    if [ -z "$(kb_features "$store" 2>/dev/null)" ]; then printf '| _none_ | | | | |\n'; fi

    # --- knowledge that exists but is not in memory/ yet ----------------------
    # AGENTS.md rule 4: harvest.md is merged at close. A loop that never closes
    # leaves it invisible to every stage start; this section makes it visible
    # from the entry page. Read-only — merging stays a deliberate step.
    body=$(kb_features "$store" 2>/dev/null | awk '$1 == "work"' | while read -r kind slug dir; do
      [ -f "$dir/harvest.md" ] || continue
      n=$(kb_body "$dir/harvest.md" | kb_count_lines)
      [ "$n" -gt 0 ] || continue
      printf '%s\t%s\t%s\n' "$slug" "$n" "$dir"
    done)
    if [ -n "$body" ]; then
      printf '\n## Knowledge not merged yet\n\n'
      printf '%s\n' "$body" | awk -F '\t' '{ n++; c += $2 } END { printf "%d open feature(s) hold %d line(s) in harvest.md that no close has merged into memory/ (AGENTS.md rule 4). `tools/kb.sh harvest` lists them with their idle time.\n", n, c }'
      printf '%s\n' "$body" | while IFS="$(printf '\t')" read -r slug n dir; do
        [ -n "${slug:-}" ] || continue
        printf '\n### %s — %s line(s) · [harvest.md](work/%s/harvest.md)\n\n' "$slug" "$n" "$slug"
        kb_body "$dir/harvest.md" | kb_print_bounded "$HARVEST_INDEX_MAX" "" "work/$slug/harvest.md"
      done
    fi

    # --- one section per feature ----------------------------------------------
    for kind in work archive; do
      [ -d "$store/$kind" ] || continue
      case "$kind" in
        work) printf '\n## Open features\n';;
        archive) printf '\n## Closed features\n';;
      esac
      kb_features_sorted "$store" "$kind" | while IFS="$(printf '\t')" read -r key kind slug dir; do
        [ -n "${slug:-}" ] || continue
        state=$(kb_state "$dir")
        goal=$(kb_title "$dir")
        track=$(kb_real "$(kb_field "$dir/intent.md" Track 2>/dev/null || true)")
        date=$(kb_date "$dir" "$slug")
        tags=$(kb_tags "$dir")
        [ "$style" = obsidian ] && [ -n "$tags" ] && tags=$(kb_hashtags "$tags")
        when=""
        [ -n "$date" ] && when=" · $date"
        if [ "$kind" = archive ]; then f=$(kb_closed_at "$dir"); [ -n "$f" ] && when="$when · closed $f"; fi
        printf '\n### %s — %s%s%s\n' "$slug" "$state" "$when" "${tags:+ · $tags}"
        [ -n "$goal" ] && printf '\n%s\n' "$goal"
        body=$(kb_summary "$dir")
        if [ -n "$body" ]; then printf '\n'; printf '%s\n' "$body" | kb_print_bounded "$SUMMARY_MAX" "" "$kind/$slug/$(kb_summary_where "$dir")"; fi
        [ -n "$track" ] && printf '\nTrack: %s\n' "$track"
        if [ -f "$dir/CLOSED" ]; then
          f=$(awk '/^reason: /{sub(/^reason: /,""); sub(/[ \t\r]*$/,""); print; exit}' "$dir/CLOSED")
          [ -n "$f" ] && printf '\nClosed: %s\n' "$f"
        fi
        printf '\n'
        for doc in $KB_DOCS; do
          [ -f "$dir/$doc" ] && printf -- '- [%s](%s/%s/%s)\n' "$doc" "$kind" "$slug" "$doc"
        done
        [ -f "$dir/harvest.md" ] && printf -- '- [harvest.md](%s/%s/harvest.md) — not merged into memory/ yet\n' "$kind" "$slug"
        kb_lessons "$store" "$slug" | while read -r f; do
          printf -- '- [lesson: %s](memory/lessons/%s)\n' "$(kb_h1 "$f" "Lesson: ")" "$(basename "$f")"
        done
      done
      # `wrote` cannot survive the subshell above; report emptiness by looking again
      if [ -z "$(kb_features "$store" 2>/dev/null | awk -v k="$kind" '$1 == k')" ]; then
        printf '\n_none_\n'
      fi
    done
    printf '\n## Memory\n\n'
    for f in POLICY.md INDEX.md DOMAIN.md; do
      [ -f "$store/memory/$f" ] && printf -- '- [%s](memory/%s)\n' "$f" "$f"
    done
    [ -d "$store/memory/lessons" ] && printf -- '- [lessons/](memory/lessons/)\n'
    [ -f "$store/config.md" ] && printf -- '- [config.md](config.md)\n'
    printf ''
  } > "$page.kb-tmp.$$" 2>/dev/null || {
    rm -f "$page.kb-tmp.$$"; echo "FAIL: cannot write $page" >&2; return 2; }
  mv "$page.kb-tmp.$$" "$page" || { rm -f "$page.kb-tmp.$$"; echo "FAIL: cannot write $page" >&2; return 2; }
  echo "contents page: $page${style:+ ($style)}"
}

# --- list --------------------------------------------------------------------
kb_list() { # <store>
  local store="$1" n=0
  printf '%s\n' "$(kb_label "$store")"
  while read -r kind slug dir; do
    [ -n "${slug:-}" ] || continue
    printf '  %-9s %-28s %s\n' "$kind" "$slug" "$(kb_state "$dir")"
    n=$((n + 1))
  done <<EOF
$(kb_features "$store" 2>/dev/null)
EOF
  [ "$n" -gt 0 ] || printf '  (no features)\n'
  return 0
}

# --- show --------------------------------------------------------------------
# A digest, not a table of contents: what the feature is for, where it stands,
# what it learned — then the paths. Every line comes from a record; nothing is
# summarized by this tool, only selected and bounded.
kb_show() { # <store> <slug> → 0 when found
  local store="$1" slug="$2" kind dir doc found=1 v f meta body
  for kind in work archive; do
    dir="$store/$kind/$slug"
    [ -d "$dir" ] || continue
    [ -L "$dir" ] && { echo "note: $dir is a symlink — not read" >&2; continue; }
    found=0
    printf '%s/%s/%s — %s\n' "$(kb_label "$store")" "$kind" "$slug" "$(kb_state "$dir")"
    v=$(kb_title "$dir"); [ -n "$v" ] && printf '  %s\n' "$v"
    meta=""
    for v in Track Type Date Tags "Requested by" Refs; do
      f=$(kb_real "$(kb_field "$dir/intent.md" "$v" 2>/dev/null || true)")
      [ -n "$f" ] && meta="$meta · $v: $f"
    done
    [ -n "$meta" ] && printf '  %s\n' "${meta# · }"
    body=$(kb_summary "$dir")
    if [ -n "$body" ]; then
      printf '  Summary:\n'
      printf '%s\n' "$body" | kb_print_bounded "$SUMMARY_MAX" "    " "$kind/$slug/$(kb_summary_where "$dir")"
    fi
    v=$(kb_real "$(kb_field "$dir/delivery.md" Target 2>/dev/null || true)")
    if [ -n "$v" ]; then
      printf '  Delivered: %s' "$v"
      f=$(kb_real "$(kb_field "$dir/delivery.md" Confirmed 2>/dev/null || true)"); [ -n "$f" ] && printf ' (confirmed: %s)' "$f"
      f=$(kb_real "$(kb_field "$dir/delivery.md" Handoff 2>/dev/null || true)"); [ -n "$f" ] && printf ' · handoff: %s' "$f"
      printf '\n'
    fi
    if [ -f "$dir/CLOSED" ]; then
      printf '  Closed: %s' "$(awk '/^reason: /{sub(/^reason: /,""); sub(/[ \t\r]*$/,""); print; exit}' "$dir/CLOSED")"
      f=$(kb_closed_at "$dir"); [ -n "$f" ] && printf ' (%s)' "$f"
      printf '\n'
    fi
    if [ -f "$dir/harvest.md" ]; then
      body=$(kb_body "$dir/harvest.md")
      if [ -n "$body" ]; then
        printf '  Not merged into memory/ yet (harvest.md):\n'
        printf '%s\n' "$body" | kb_print_bounded "$HARVEST_MAX" "    " "$kind/$slug/harvest.md"
      fi
    fi
    v=$(kb_lessons "$store" "$slug")
    if [ -n "$v" ]; then
      printf '  Lessons:\n'
      printf '%s\n' "$v" | while read -r f; do
        printf '    %s — memory/lessons/%s\n' "$(kb_h1 "$f" "Lesson: ")" "$(basename "$f")"
      done
    fi
    printf '  Documents:\n'
    for doc in $KB_DOCS harvest.md; do
      [ -f "$dir/$doc" ] && printf '    %s/%s/%s\n' "$kind" "$slug" "$doc"
    done
  done
  return $found
}

# --- harvest -----------------------------------------------------------------
# Which open features hold knowledge that is not in memory/ yet, and for how
# long nobody has touched them. This is the trigger the close-only merge
# lacked: rule 4 makes close the merge moment, and a feature that never closes
# never merges. A feature idle past --stale may be merged WITHOUT closing (the
# same procedure, one at a time, in the owning checkout — AGENTS.md rule 4);
# this command only reports, it writes nothing.
kb_harvest() { # <store> <stale-days> → prints; echoes "<found> <stale>" on fd 3
  local store="$1" stale="$2" kind slug dir n idle flag found=0 nstale=0
  printf '%s\n' "$(kb_label "$store")"
  while read -r kind slug dir; do
    [ -n "${slug:-}" ] || continue
    [ -f "$dir/harvest.md" ] || continue
    n=$(kb_body "$dir/harvest.md" | kb_count_lines)
    [ "$n" -gt 0 ] || continue
    found=$((found + 1))
    idle=$(kb_idle_days "$dir")
    if [ -z "$idle" ]; then flag="idle: unknown"
    elif [ "$idle" -ge "$stale" ]; then flag="STALE — idle ${idle}d (≥ ${stale}d): merge without closing"; nstale=$((nstale + 1))
    else flag="active — idle ${idle}d"; fi
    printf '  %-32s %3s line(s)   %s\n' "$slug" "$n" "$flag"
  done <<EOF
$(kb_features "$store" 2>/dev/null | awk '$1 == "work"')
EOF
  [ "$found" -gt 0 ] || printf '  (no unmerged harvest)\n'
  echo "$found $nstale" >&3
}

# --- search ------------------------------------------------------------------
# Literal only (grep -F): a query is text a human remembers, not a regex, and a
# stray `.` or `*` must not silently widen the search. `-e` keeps a query that
# starts with `-` a query.
kb_searchable() { # <store> → readable record paths, one per line
  local store="$1" d
  for d in work archive memory; do
    [ -d "$store/$d" ] || continue
    find "$store/$d" -type f \( -name '*.md' -o -name 'CLOSED' \) 2>/dev/null
  done | awk '
    $0 ~ /\/scratch\// { next }
    $0 ~ /\/approvals\// { next }
    { n = split($0, p, "/"); b = p[n] }
    b == "progress.md" || b == "baseline.txt" || b == "checkpoint.md" || b == "verify-receipt.md" { next }
    { print }
  ' | LC_ALL=C sort
}
kb_search() { # <store> <query> <limit> <shown-so-far> → prints, echoes the new count on fd 3
  local store="$1" q="$2" limit="$3" shown="$4" label f rel hits
  label=$(kb_label "$store")
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    hits=$(grep -F -n -e "$q" -- "$f" 2>/dev/null) || continue
    rel=${f#"$store"/}
    while IFS= read -r h; do
      [ -n "$h" ] || continue
      if [ "$shown" -ge "$limit" ]; then shown=$((shown + 1)); continue; fi
      printf '%s/%s:%s\n' "$label" "$rel" "$(printf '%s' "$h" | cut -c1-$LINE_MAX)"
      shown=$((shown + 1))
    done <<EOF
$hits
EOF
  done <<EOF
$(kb_searchable "$store")
EOF
  echo "$shown" >&3
}

# --- argument parsing --------------------------------------------------------
[ $# -ge 1 ] || usage
cmd="$1"; shift
# One positional argument at most (a slug, or the literal to search for). Flags
# may follow it. A query that starts with `-` goes after `--`; an unknown option
# is an error, never a silently ignored word.
store=""; area=""; limit=50; stale=30; style=""; arg=""; have_arg=0; endopts=0
while [ $# -gt 0 ]; do
  if [ "$endopts" -eq 0 ]; then
    case "$1" in
      --) endopts=1; shift; continue;;
      --store) [ $# -ge 2 ] || usage; store="$2"; shift 2; continue;;
      --store=*) store="${1#--store=}"; shift; continue;;
      --area) [ $# -ge 2 ] || usage; area="$2"; shift 2; continue;;
      --area=*) area="${1#--area=}"; shift; continue;;
      --limit) [ $# -ge 2 ] || usage; limit="$2"; shift 2; continue;;
      --limit=*) limit="${1#--limit=}"; shift; continue;;
      --stale) [ $# -ge 2 ] || usage; stale="$2"; shift 2; continue;;
      --stale=*) stale="${1#--stale=}"; shift; continue;;
      --obsidian) style=obsidian; shift; continue;;
      -h|--help) usage;;
      -?*) echo "FAIL: unknown option '$1' (a query starting with '-' goes after --)" >&2; exit 2;;
    esac
  fi
  [ "$have_arg" -eq 0 ] || { echo "FAIL: one argument at most; quote a query that contains spaces" >&2; exit 2; }
  arg="$1"; have_arg=1; shift
done
if [ "$have_arg" -eq 1 ]; then set -- "$arg"; else set --; fi
case "$limit" in (''|*[!0-9]*) echo "FAIL: --limit takes a number" >&2; exit 2;; esac
[ "$limit" -gt 0 ] || { echo "FAIL: --limit must be > 0" >&2; exit 2; }
case "$stale" in (''|*[!0-9]*) echo "FAIL: --stale takes a number of days" >&2; exit 2;; esac
[ "$style" = obsidian ] && [ "$cmd" != index ] && { echo "FAIL: --obsidian applies to index only" >&2; exit 2; }

stores=$(kb_stores "$store" "$area") || exit 2

rc=0
case "$cmd" in
  index)
    [ -z "$area" ] || { echo "FAIL: index writes one store's page — use --store" >&2; exit 2; }
    # `index` is the one WRITE this tool performs. Against the default store —
    # this project's ./.sdlc, which may be a link into an external area — it runs
    # the same ownership check the gates run, so a copied checkout cannot write
    # into the original's store (gates/_common.sh sdlc_store_owner_ok). An
    # explicit --store is a deliberate choice of a store and is not second-guessed;
    # reading (list, show, search, harvest) is never bound to a checkout at all.
    if [ -z "$store" ]; then
      kb_kit=$(cd "$(dirname "$0")/.." 2>/dev/null && pwd) || kb_kit=""
      [ -n "$kb_kit" ] && [ -f "$kb_kit/gates/_common.sh" ] || {
        echo "FAIL: gates/_common.sh is not next to $0 — the ownership check cannot run" >&2; exit 2; }
      . "$kb_kit/gates/_common.sh"
      sdlc_store_owner_ok || exit 2
    fi
    kb_index "$stores" "$(kb_index_style "$stores" "$style")" || exit $?;;
  list)
    while IFS= read -r s; do [ -n "$s" ] && kb_list "$s"; done <<EOF
$stores
EOF
    ;;
  show)
    [ $# -ge 1 ] || { echo "FAIL: show needs a feature slug" >&2; exit 2; }
    slug="$1"; rc=1
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      if kb_show "$s" "$slug"; then rc=0; fi
    done <<EOF
$stores
EOF
    [ "$rc" -eq 0 ] || echo "no feature '$slug' in the store(s) searched" >&2;;
  harvest)
    [ $# -eq 0 ] || { echo "FAIL: harvest takes no argument (use --stale <days>)" >&2; exit 2; }
    total=0; tstale=0
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      counts=$(kb_harvest "$s" "$stale" 3>&1 >&4)
      total=$((total + ${counts% *})); tstale=$((tstale + ${counts#* }))
    done 4>&1 <<EOF
$stores
EOF
    if [ "$total" -eq 0 ]; then
      echo "no unmerged harvest — every candidate is in memory/ (or no feature wrote one)" >&2; rc=1
    else
      echo "$total unmerged harvest(s), $tstale idle ≥ ${stale} day(s)."
      echo "Merge (AGENTS.md rule 4): read work/<slug>/harvest.md → lesson files + INDEX.md lines + DOMAIN.md facts, then delete harvest.md."
      echo "A STALE feature may be merged without closing; it stays open. One merge at a time, in the owning checkout."
    fi;;
  search)
    [ $# -ge 1 ] || { echo "FAIL: search needs the text to look for" >&2; exit 2; }
    q="$1"
    [ -n "$q" ] || { echo "FAIL: empty search text" >&2; exit 2; }
    shown=0
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      shown=$(kb_search "$s" "$q" "$limit" "$shown" 3>&1 >&4)
    done 4>&1 <<EOF
$stores
EOF
    if [ "$shown" -eq 0 ]; then
      echo "no match for '$q'" >&2; rc=1
    elif [ "$shown" -gt "$limit" ]; then
      echo "… $((shown - limit)) more match(es) not shown (--limit $limit)" >&2
    fi;;
  *) echo "FAIL: unknown command '$cmd'" >&2; usage;;
esac
exit $rc
