#!/usr/bin/env bash
# kb.sh — read the records back. The loop WRITES knowledge (intent, spec, plan,
# evidence, delivery, CLOSED, lessons); this is how a later feature FINDS it.
#
#   kb.sh index  [--store <dir>]                  regenerate the contents page
#   kb.sh list   [--store <dir> | --area <folder>]
#   kb.sh show   <slug> [--store <dir> | --area <folder>]
#   kb.sh search [--store <dir> | --area <folder>] [--limit N] <literal text>
#
# Store resolution: --store <dir> is a store (or a project's .sdlc); with
# neither flag the store is ./.sdlc. --area <folder> reads EVERY recognized
# store in that folder — a directory holding a PROJECT record written by
# init.sh --area — and nothing else: no arbitrary filesystem content, no
# symlinks followed, one level deep. The original checkout need not exist, so
# knowledge survives a deleted worktree.
#
# What is read: *.md and CLOSED under work/, archive/ and memory/.
# Never read: scratch/ (bulk evidence), approvals/ (machine records),
# progress.md (heartbeat), baseline.txt, checkpoint.md, verify-receipt.md.
#
# Nothing under work/ or archive/ is ever written — an approval-bound artifact
# cannot change because the page was regenerated. `index` writes exactly one
# file, <store>/README.md, and refuses to overwrite one it did not generate.
#
# Exit codes: 0 done / matches found, 1 nothing found (no match, unknown slug),
# 2 usage error or refusal (missing store, unowned path, unwritable page).
set -u

MARKER='<!-- generated by sdlc-kit tools/kb.sh — regenerated by init.sh and close.sh; edits are overwritten -->'
LINE_MAX=200

usage() {
  sed -n '3,9p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 2
}

# --- store resolution --------------------------------------------------------
kb_is_store() { # <dir> — a directory that holds records
  [ -d "$1/work" ] || [ -d "$1/archive" ] || [ -d "$1/memory" ]
}
kb_label() { # <store dir> → the name results are reported under
  local s="$1" p
  p=$(cd "$s" 2>/dev/null && pwd -P) || { basename "$s"; return; }
  basename "$p"
}
# Prints one store path per line, or fails with a reason on stderr.
kb_stores() { # <store-or-empty> <area-or-empty>
  local store="$1" area="$2" d n=0
  if [ -n "$area" ]; then
    [ -d "$area" ] || { echo "FAIL: no such area: $area" >&2; return 2; }
    for d in "$area"/*; do
      [ -d "$d" ] || continue
      [ -L "$d" ] && continue          # never follow a link out of the area
      [ -f "$d/PROJECT" ] || continue  # only stores this kit owns
      printf '%s\n' "$d"; n=$((n + 1))
    done
    [ "$n" -gt 0 ] || { echo "FAIL: no sdlc-kit stores in $area (a store holds a PROJECT record)" >&2; return 2; }
    return 0
  fi
  [ -n "$store" ] || store=".sdlc"
  [ -d "$store" ] || { echo "FAIL: no store at $store — run init.sh first, or pass --store/--area" >&2; return 2; }
  kb_is_store "$store" || { echo "FAIL: $store holds no work/, archive/ or memory/ — not a store" >&2; return 2; }
  printf '%s\n' "$store"
}

# --- feature reading ---------------------------------------------------------
KB_DOCS="origin.md intent.md spec.md plan.md map.md evidence.md delivery.md CLOSED"

kb_field() { # <file> <label> → the first "- <label>: value" line's value
  [ -f "$1" ] || return 1
  awk -v k="- $2:" 'index($0, k) == 1 { sub(/^[^:]*: */, ""); sub(/[ \t\r]*$/, ""); print; exit }' "$1"
}
# Feature directories of one store: "<work|archive> <slug> <dir>" lines.
kb_features() { # <store>
  local store="$1" kind d slug
  for kind in work archive; do
    [ -d "$store/$kind" ] || continue
    for d in "$store/$kind"/*; do
      [ -d "$d" ] || continue
      if [ -L "$d" ]; then
        echo "note: skipped $d — a feature directory that is a symlink is not read" >&2
        continue
      fi
      slug=$(basename "$d")
      printf '%s %s %s\n' "$kind" "$slug" "$d"
    done
  done
}
kb_lessons() { # <store> <slug> → lesson paths naming the slug
  local d="$1/memory/lessons" f
  [ -d "$d" ] || return 0
  for f in "$d"/*"$2"*; do [ -f "$f" ] && printf '%s\n' "$f"; done
}
kb_state() { # <dir> → open | the CLOSED state
  local c="$1/CLOSED"
  if [ -f "$c" ]; then awk '/^state: /{print $2; exit}' "$c"; else echo open; fi
}

# --- index -------------------------------------------------------------------
kb_index() { # <store>
  local store="$1" page kind slug dir doc goal track state f
  page="$store/README.md"
  if [ -e "$page" ]; then
    if [ -L "$page" ]; then echo "FAIL: $page is a symlink — refusing to write through it" >&2; return 2; fi
    if ! head -n 3 "$page" 2>/dev/null | grep -qF "$MARKER"; then
      echo "FAIL: $page was not generated by kb.sh — refusing to overwrite a page you wrote." >&2
      echo "  Rename it (or delete it) if you want the generated contents page here." >&2
      return 2
    fi
  fi
  {
    printf '%s\n' "$MARKER"
    printf '\n# Knowledge: %s\n\n' "$(kb_label "$store")"
    if [ -f "$store/PROJECT" ]; then
      printf 'Records of `%s` (checkout `%s`).\n\n' \
        "$(awk '/^project: /{sub(/^project: /,""); sub(/[ \t\r]*$/,""); print; exit}' "$store/PROJECT")" \
        "$(awk '/^checkout_id: /{print $2; exit}' "$store/PROJECT")"
    fi
    printf 'Search: `tools/kb.sh search "<text>"` · one feature: `tools/kb.sh show <slug>`\n'
    for kind in work archive; do
      [ -d "$store/$kind" ] || continue
      case "$kind" in
        work) printf '\n## Open features\n';;
        archive) printf '\n## Closed features\n';;
      esac
      kb_features "$store" 2>/dev/null | while read -r k slug dir; do
        [ "$k" = "$kind" ] || continue
        state=$(kb_state "$dir")
        goal=$(kb_field "$dir/intent.md" Goal 2>/dev/null || true)
        track=$(kb_field "$dir/intent.md" Track 2>/dev/null || true)
        printf '\n### %s — %s\n' "$slug" "$state"
        [ -n "$goal" ] && printf '\n%s\n' "$goal"
        [ -n "$track" ] && printf '\nTrack: %s\n' "$track"
        printf '\n'
        for doc in $KB_DOCS; do
          [ -f "$dir/$doc" ] && printf -- '- [%s](%s/%s/%s)\n' "$doc" "$kind" "$slug" "$doc"
        done
        kb_lessons "$store" "$slug" | while read -r f; do
          printf -- '- [lesson: %s](memory/lessons/%s)\n' "$(basename "$f")" "$(basename "$f")"
        done
      done
      # `wrote` cannot survive the subshell above; report emptiness by looking again
      if [ -z "$(kb_features "$store" 2>/dev/null | awk -v k="$kind" '$1 == k')" ]; then
        printf '\n_none_\n'
      fi
    done
    printf '\n## Memory\n\n'
    for f in POLICY.md INDEX.md DOMAIN.md; do
      [ -f "$store/memory/$f" ] && printf -- '- [%s](memory/%s)\n' "$f" "$f"
    done
    [ -d "$store/memory/lessons" ] && printf -- '- [lessons/](memory/lessons/)\n'
    [ -f "$store/config.md" ] && printf -- '- [config.md](config.md)\n'
    printf ''
  } > "$page.kb-tmp.$$" 2>/dev/null || {
    rm -f "$page.kb-tmp.$$"; echo "FAIL: cannot write $page" >&2; return 2; }
  mv "$page.kb-tmp.$$" "$page" || { rm -f "$page.kb-tmp.$$"; echo "FAIL: cannot write $page" >&2; return 2; }
  echo "contents page: $page"
}

# --- list --------------------------------------------------------------------
kb_list() { # <store>
  local store="$1" n=0
  printf '%s\n' "$(kb_label "$store")"
  while read -r kind slug dir; do
    [ -n "${slug:-}" ] || continue
    printf '  %-9s %-28s %s\n' "$kind" "$slug" "$(kb_state "$dir")"
    n=$((n + 1))
  done <<EOF
$(kb_features "$store" 2>/dev/null)
EOF
  [ "$n" -gt 0 ] || printf '  (no features)\n'
  return 0
}

# --- show --------------------------------------------------------------------
kb_show() { # <store> <slug> → 0 when found
  local store="$1" slug="$2" kind dir doc found=1 v f
  for kind in work archive; do
    dir="$store/$kind/$slug"
    [ -d "$dir" ] || continue
    [ -L "$dir" ] && { echo "note: $dir is a symlink — not read" >&2; continue; }
    found=0
    printf '%s/%s/%s — %s\n' "$(kb_label "$store")" "$kind" "$slug" "$(kb_state "$dir")"
    for v in Goal Track Type Date "Delivery target"; do
      f=$(kb_field "$dir/intent.md" "$v" 2>/dev/null || true)
      [ -n "$f" ] && printf '  %s: %s\n' "$v" "$f"
    done
    printf '  documents:\n'
    for doc in $KB_DOCS; do
      [ -f "$dir/$doc" ] && printf '    %s\n' "$dir/$doc"
    done
    v=$(kb_field "$dir/delivery.md" Target 2>/dev/null || true)
    [ -n "$v" ] && printf '  delivered: %s (confirmed: %s)\n' "$v" "$(kb_field "$dir/delivery.md" Confirmed 2>/dev/null || echo '-')"
    if [ -f "$dir/CLOSED" ]; then
      printf '  closed: %s\n' "$(awk '/^reason: /{sub(/^reason: /,""); print; exit}' "$dir/CLOSED")"
    fi
    v=$(kb_lessons "$store" "$slug")
    if [ -n "$v" ]; then
      printf '  lessons:\n'
      printf '%s\n' "$v" | while read -r f; do printf '    %s\n' "$f"; done
    fi
  done
  return $found
}

# --- search ------------------------------------------------------------------
# Literal only (grep -F): a query is text a human remembers, not a regex, and a
# stray `.` or `*` must not silently widen the search. `-e` keeps a query that
# starts with `-` a query.
kb_searchable() { # <store> → readable record paths, one per line
  local store="$1" d
  for d in work archive memory; do
    [ -d "$store/$d" ] || continue
    find "$store/$d" -type f \( -name '*.md' -o -name 'CLOSED' \) 2>/dev/null
  done | awk '
    $0 ~ /\/scratch\// { next }
    $0 ~ /\/approvals\// { next }
    { n = split($0, p, "/"); b = p[n] }
    b == "progress.md" || b == "baseline.txt" || b == "checkpoint.md" || b == "verify-receipt.md" { next }
    { print }
  ' | LC_ALL=C sort
}
kb_search() { # <store> <query> <limit> <shown-so-far> → prints, echoes the new count on fd 3
  local store="$1" q="$2" limit="$3" shown="$4" label f rel hits
  label=$(kb_label "$store")
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    hits=$(grep -F -n -e "$q" -- "$f" 2>/dev/null) || continue
    rel=${f#"$store"/}
    while IFS= read -r h; do
      [ -n "$h" ] || continue
      if [ "$shown" -ge "$limit" ]; then shown=$((shown + 1)); continue; fi
      printf '%s/%s:%s\n' "$label" "$rel" "$(printf '%s' "$h" | cut -c1-$LINE_MAX)"
      shown=$((shown + 1))
    done <<EOF
$hits
EOF
  done <<EOF
$(kb_searchable "$store")
EOF
  echo "$shown" >&3
}

# --- argument parsing --------------------------------------------------------
[ $# -ge 1 ] || usage
cmd="$1"; shift
# One positional argument at most (a slug, or the literal to search for). Flags
# may follow it. A query that starts with `-` goes after `--`; an unknown option
# is an error, never a silently ignored word.
store=""; area=""; limit=50; arg=""; have_arg=0; endopts=0
while [ $# -gt 0 ]; do
  if [ "$endopts" -eq 0 ]; then
    case "$1" in
      --) endopts=1; shift; continue;;
      --store) [ $# -ge 2 ] || usage; store="$2"; shift 2; continue;;
      --store=*) store="${1#--store=}"; shift; continue;;
      --area) [ $# -ge 2 ] || usage; area="$2"; shift 2; continue;;
      --area=*) area="${1#--area=}"; shift; continue;;
      --limit) [ $# -ge 2 ] || usage; limit="$2"; shift 2; continue;;
      --limit=*) limit="${1#--limit=}"; shift; continue;;
      -h|--help) usage;;
      -?*) echo "FAIL: unknown option '$1' (a query starting with '-' goes after --)" >&2; exit 2;;
    esac
  fi
  [ "$have_arg" -eq 0 ] || { echo "FAIL: one argument at most; quote a query that contains spaces" >&2; exit 2; }
  arg="$1"; have_arg=1; shift
done
if [ "$have_arg" -eq 1 ]; then set -- "$arg"; else set --; fi
case "$limit" in (''|*[!0-9]*) echo "FAIL: --limit takes a number" >&2; exit 2;; esac
[ "$limit" -gt 0 ] || { echo "FAIL: --limit must be > 0" >&2; exit 2; }

stores=$(kb_stores "$store" "$area") || exit 2

rc=0
case "$cmd" in
  index)
    [ -z "$area" ] || { echo "FAIL: index writes one store's page — use --store" >&2; exit 2; }
    # `index` is the one WRITE this tool performs. Against the default store —
    # this project's ./.sdlc, which may be a link into an external area — it runs
    # the same ownership check the gates run, so a copied checkout cannot write
    # into the original's store (gates/_common.sh sdlc_store_owner_ok). An
    # explicit --store is a deliberate choice of a store and is not second-guessed;
    # reading (list, show, search) is never bound to a checkout at all.
    if [ -z "$store" ]; then
      kb_kit=$(cd "$(dirname "$0")/.." 2>/dev/null && pwd) || kb_kit=""
      [ -n "$kb_kit" ] && [ -f "$kb_kit/gates/_common.sh" ] || {
        echo "FAIL: gates/_common.sh is not next to $0 — the ownership check cannot run" >&2; exit 2; }
      . "$kb_kit/gates/_common.sh"
      sdlc_store_owner_ok || exit 2
    fi
    kb_index "$stores" || exit $?;;
  list)
    while IFS= read -r s; do [ -n "$s" ] && kb_list "$s"; done <<EOF
$stores
EOF
    ;;
  show)
    [ $# -ge 1 ] || { echo "FAIL: show needs a feature slug" >&2; exit 2; }
    slug="$1"; rc=1
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      if kb_show "$s" "$slug"; then rc=0; fi
    done <<EOF
$stores
EOF
    [ "$rc" -eq 0 ] || echo "no feature '$slug' in the store(s) searched" >&2;;
  search)
    [ $# -ge 1 ] || { echo "FAIL: search needs the text to look for" >&2; exit 2; }
    q="$1"
    [ -n "$q" ] || { echo "FAIL: empty search text" >&2; exit 2; }
    shown=0
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      shown=$(kb_search "$s" "$q" "$limit" "$shown" 3>&1 >&4)
    done 4>&1 <<EOF
$stores
EOF
    if [ "$shown" -eq 0 ]; then
      echo "no match for '$q'" >&2; rc=1
    elif [ "$shown" -gt "$limit" ]; then
      echo "… $((shown - limit)) more match(es) not shown (--limit $limit)" >&2
    fi;;
  *) echo "FAIL: unknown command '$cmd'" >&2; usage;;
esac
exit $rc
